services:
  patroni1:
    build:
      target: patroni-monolith
    image: jepsen-patroni-monolith:latest

  patroni2:
    build:
      target: patroni-monolith
    image: jepsen-patroni-monolith:latest

  patroni3:
    build:
      target: patroni-monolith
    image: jepsen-patroni-monolith:latest
